=== vasilhristov1/XML-FMI-2021-2022/Project/XML2022_ProjectNo55/AttributeToElementComplex/attr_focused_complex.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT NAMM_ITEM (SupplierId|Items)*>
        <!ATTLIST NAMM_ITEM
                version CDATA #REQUIRED>
        <!ELEMENT SupplierId (#PCDATA)>
        <!ELEMENT Items (Item)*>
        <!ELEMENT Item (Supplier|ItemDesc|ItemDescLong|RetailValue|UCValue|CountryOrigin|BrandName|Length|Width|Height|DimUOM|Weight|WeightUOM|BarCode|C|Kit|Serialized|AnnounceDate|AvailableDate|Warranty|Category|Images|ImageURL|ProductURL)*>
        <!ELEMENT Supplier (#PCDATA)>
        <!ATTLIST Supplier
                ItemId CDATA #REQUIRED
                Model CDATA #REQUIRED>
        <!ELEMENT ItemDesc (#PCDATA)>
        <!ELEMENT ItemDescLong (#PCDATA)>
        <!ELEMENT RetailValue (#PCDATA)>
        <!ELEMENT UCValue (#PCDATA)>
        <!ELEMENT CountryOrigin (#PCDATA)>
        <!ELEMENT BrandName (#PCDATA)>
        <!ELEMENT Length (#PCDATA)>
        <!ELEMENT Width (#PCDATA)>
        <!ELEMENT Height (#PCDATA)>
        <!ELEMENT DimUOM (#PCDATA)>
        <!ELEMENT Weight (#PCDATA)>
        <!ELEMENT WeightUOM (#PCDATA)>
        <!ELEMENT BarCode (#PCDATA)>
        <!ATTLIST BarCode
                Desc CDATA #REQUIRED
                Id CDATA #REQUIRED>
        <!ELEMENT C (#PCDATA)>
        <!ATTLIST C
                DimUOM CDATA #REQUIRED
                Height CDATA #REQUIRED
                Length CDATA #REQUIRED
                QtyPerUOM CDATA #REQUIRED
                UOM CDATA #REQUIRED
                Weight CDATA #REQUIRED
                WeightUOM CDATA #REQUIRED
                Width CDATA #REQUIRED>
        <!ELEMENT Kit (#PCDATA)>
        <!ELEMENT Serialized (#PCDATA)>
        <!ELEMENT AnnounceDate (#PCDATA)>
        <!ELEMENT AvailableDate (#PCDATA)>
        <!ELEMENT Warranty (#PCDATA)>
        <!ATTLIST Warranty
                LabTerm CDATA #REQUIRED
                LabUOM CDATA #REQUIRED
                PartTerm CDATA #REQUIRED
                PartUOM CDATA #REQUIRED>
        <!ELEMENT Category (#PCDATA)>
        <!ELEMENT Images (#PCDATA)>
        <!ELEMENT ImageURL (#PCDATA)>
        <!ELEMENT ProductURL (#PCDATA)>

=== vasilhristov1/XML-FMI-2021-2022/Project/XML2022_ProjectNo55/AttributeToElementComplex/XML_Attr_Focused_Complex.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NAMM_ITEM SYSTEM "attr_focused_complex.dtd">
<NAMM_ITEM version="2007.1">
    <SupplierId>0761294001004</SupplierId>
    <Items>
        <Item>
            <Supplier ItemId="FantomX6" Model="Fantom-X6" />
            <ItemDesc>Workstation Keyboard</ItemDesc>
            <ItemDescLong>Powerhouse Workstation with an Ultra-Friendly Interface</ItemDescLong>
            <RetailValue>2395</RetailValue>
            <UCValue>1437</UCValue>
            <CountryOrigin>China</CountryOrigin>
            <BrandName>Roland</BrandName>
            <Length>1050</Length>
            <Width>358</Width>
            <Height>125</Height>
            <DimUOM>mm</DimUOM>
            <Weight>12.5</Weight>
            <WeightUOM>kg</WeightUOM>
            <BarCode Desc="UPC" Id="761294084991" />
            <C DimUOM="In" Height="6" Length="43" QtyPerUOM="1" UOM="EA" Weight="13" WeightUOM="kg" Width="15" />
            <Kit>false</Kit>
            <Serialized>true</Serialized>
            <AnnounceDate>2006-01-15</AnnounceDate>
            <AvailableDate>2006-02-24</AvailableDate>
            <Warranty LabTerm="365" LabUOM="Day" PartTerm="90" PartUOM="Day" />
            <Category>Keyboard</Category>
            <Images>FantomX6.jpg</Images>
            <ImageURL>http://www.rolandus.com/press/images</ImageURL>
            <ProductURL>http://www.rolandus.com/products/productdetails.aspx?ObjectId=581</ProductURL>
        </Item>
    </Items>
</NAMM_ITEM>
